### ISSUE TITLE
Feature Request: Add Support for Brush-Based Collisions (wrbrushes)

### ISSUE THREAD

**Issue by daniel-abbott** [jitspoe/godot_bsp_importer#21]
ericw-tools `qbsp` tool supports compiling maps with a list of brushes for brush-based collisions, which might be useful for faster and more accurate generation of StaticBody3D collision geometry over the current two approaches.

Further, this opens the door to per-body physics materials - example: take all the brushes with a "stone" texture and put all of those collision bodies under a single static body, which can then receive a "stone" physics material.

https://ericw-tools.readthedocs.io/en/latest/qbsp.html#cmdoption-qbsp-wrbrushes

**Comment by jitspoe** [comment]
Using the brushes would definitely be more optimal.  Not sure how significant it would be, considering physics collision calculations are typically O(log n).  The Quake2 format also stores the brush data.  I'd like to get both of these in at some point, but I don't know when it'll happen.  Feel free to make a PR if it's something you need sooner rather than later!  I think @Yagich was planning to look at Q2 BSP support.  Quake 3 support might also be nice.

I think getting the texture info might be possible even without the brush data.  The challenge there is, if a brush has multiple textures, what would you use for the physics material?  Ex: Something might have grass on the top and rock on the side.  I guess something is better than nothing!

**Comment by daniel-abbott** [comment]
Fair point about the multi-textured brushes, Q1 maps don't support surface flags - I believe both the Q2 and the Half-Life BSP format does, I can't remember if Q3 does but I _think_ so...

Maybe we should just create a new BSP format, with hookers and blackjack

**Comment by jitspoe** [comment]
Yeah, I've definitely considered extending ericw-tools with a special format that simply does the CSG stuff for the meshes and doesn't do any BSP splitting.  Not sure how involved that would be.

**Comment by jitspoe** [comment]
Made some progress on this today.  The additional brush info does not contain anything about textures, though.  It only has the bounds of the brush for collision.  Hopefully this will help with some of the physics performance issues I've been running into with more complex maps.

**Comment by jitspoe** [comment]
Implmented in ce338f2ccd17b61c6b9f3ee08b2394249026d7e8

**Comment by daniel-abbott** [comment]
Thanks! I guess I was too optimistic about directly tying the visual geometry to the collision geometry, the possibility for improved physics performance though is still exciting, I'll give this some testing myself.

**Comment by jitspoe** [comment]
In order to do that, we'd have to go through all the textured polygons and attempt to find a matching plane in the collision.  It could be done, but would probably slow down the import quite a bit (and there's also the issue of multiple textures per brush to deal with).
